### ISSUE TITLE
java.lang.NullPointerException when switching profiles.

### ISSUE THREAD

**Issue by kehh** [mskonovalov/intellij-hidpi-profiles#6]
I'm not sure if it's relevant but I'm using both this profile and also the Material Theme UI EAP plugin. PHPStorm 2017.2.4
```
null
java.lang.NullPointerException
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1644)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1273)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:276)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1503)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1261)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:253)
	at javax.swing.text.html.StyleSheet$ViewAttributeSet.<init>(StyleSheet.java:2673)
	at javax.swing.text.html.StyleSheet.getViewAttributes(StyleSheet.java:348)
	at javax.swing.text.html.ParagraphView.setPropertiesFromAttributes(ParagraphView.java:101)
	at javax.swing.text.ParagraphView.<init>(ParagraphView.java:59)
	at javax.swing.text.html.ParagraphView.<init>(ParagraphView.java:54)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory.create(HTMLEditorKit.java:1148)
	at com.intellij.notification.impl.NotificationsManagerImpl$5$1.create(NotificationsManagerImpl.java:369)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:112)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory$BodyBlockView.setParent(HTMLEditorKit.java:1327)
	at javax.swing.text.CompositeView.replace(CompositeView.java:217)
	at javax.swing.text.BoxView.replace(BoxView.java:181)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:114)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setView(BasicTextUI.java:1328)
	at javax.swing.plaf.basic.BasicTextUI.setView(BasicTextUI.java:693)
	at javax.swing.plaf.basic.BasicTextUI.modelChanged(BasicTextUI.java:682)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.propertyChange(BasicTextUI.java:1794)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8436)
	at javax.swing.text.JTextComponent.setDocument(JTextComponent.java:443)
	at javax.swing.JEditorPane.setEditorKit(JEditorPane.java:1055)
	at com.intellij.notification.impl.NotificationsManagerImpl.createBalloon(NotificationsManagerImpl.java:366)
	at com.intellij.notification.impl.NotificationsManagerImpl.createBalloon(NotificationsManagerImpl.java:316)
	at com.intellij.notification.impl.NotificationsManagerImpl.a(NotificationsManagerImpl.java:266)
	at com.intellij.notification.impl.NotificationsManagerImpl.c(NotificationsManagerImpl.java:183)
	at com.intellij.notification.impl.NotificationsManagerImpl.a(NotificationsManagerImpl.java:146)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:396)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:398)
	at com.intellij.notification.impl.NotificationsManagerImpl.b(NotificationsManagerImpl.java:151)
	at com.intellij.notification.impl.NotificationsManagerImpl.access$700(NotificationsManagerImpl.java:90)
	at com.intellij.notification.impl.NotificationsManagerImpl$MyNotificationListener.notify(NotificationsManagerImpl.java:1089)
	at sun.reflect.GeneratedMethodAccessor801.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:443)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:381)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:374)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy120.notify(Unknown Source)
	at com.intellij.notification.Notifications$Bus.doNotify(Notifications.java:75)
	at com.intellij.notification.Notifications$Bus.lambda$notify$1(Notifications.java:69)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2760)
	at com.intellij.notification.Notifications$Bus.notify(Notifications.java:69)
	at ms.konovalov.intellij.hidpi.FontSizeAction.lambda$notify$1(FontSizeAction.java:75)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1030)
	at ms.konovalov.intellij.hidpi.FontSizeAction.notify(FontSizeAction.java:71)
	at ms.konovalov.intellij.hidpi.FontSizeAction.setSelected(FontSizeAction.java:45)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:117)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
![screenshot from 2017-11-09 14-52-41](https://user-images.githubusercontent.com/12571/32592200-ad630b82-c55d-11e7-953c-25c000c2bd22.png)

**Comment by mskonovalov** [comment]
@kehh could you please check it again in new version
